
include: package:lints/recommended.yaml

analyzer:
  errors:
    camel_case_extensions: ignore
  language:
    strict-casts: true # Never implicitly cast from a "dynamic"
    #strict-inference: true # Never choose "dynamic" when type cannot be determined with "final" and "var"
    #strict-raw-types: true # Never choose "dynamic" when the type of a generic cannot be determined
