name: rust_core
description: A pure Dart implementation of Rust patterns. Types include Result, Option, Cell, Slice, Array, Iterator, etc. Facilitates functional programming and error handling.
version: 1.3.4
repository: https://github.com/mcmah309/rust

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
