name: rust
description: A pure Dart implementation of Rust patterns. Types include Result, Option, Cell, Slice, Array, Iterator, Channels, Mutex, etc.
version: 2.0.0
repository: https://github.com/mcmah309/rust

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  meta: ^1.0.0
  path: ^1.0.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
