name: rust_core
description: Pure Dart implementation of patterns in Rust's core library. Types include Result, Option, Cell, Slice, Array, Iterator, etc. Facilitates functional programming and error handling.
version: 1.3.3
repository: https://github.com/mcmah309/rust_core

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
